---
- hosts: servers
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: restart 
      service:
        name: httpd
        state: restarted      

    - name: copy index.html
      copy:
        src: index.html
        dest: /var/www/html
        remote_src: yes  
        
    - name: restart
      service:
        name: httpd
        state: restarted
